name: Deploy PropertyWala_client 

on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t neam6009/propertywala_frontend  . 


      - name: Publish Image to docker hub
        run: docker push neam6009/propertywala_frontend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull neam6009/propertywala_frontend:latest 
      - name: Delete old container
        run: docker rm -f propertyWala-frontend-container 
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name propertyWala-frontend-container neam6009/propertywala_frontend 